### ISSUE TITLE
Don't break inside article

### ISSUE THREAD

**Issue by alienlebarge** [alienlebarge/dayone-export-template#2]
Do not break inside `<article>`.
The `page-break-inside: avoid;` value have to be used inside a `@media print {...}`
See [this CSS-Tricks article](http://css-tricks.com/almanac/properties/p/page-break/)

``` css
@media print {
  article {
    page-break-inside: avoid;
  }
}
```
